# Generated by Django 6.0.2 on 2026-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_fix_socialapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email for budget notifications.', max_length=254, null=True),
        ),
    ]
